sitelove/sitelove/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('', views.nav, name="nav"),
    path('admin/', admin.site.urls),
    path('vitrine/', include("vitrine.urls"))
]

sitelove/vitrine/urls.py
from django.urls import path
from . import views

app_name = 'vitrine'

urlpatterns = [
    path('', views.about, name="about"),
    path('', views.contact, name="contact"),
]

sitelove/vitrine/models.py
from django.db import models

# Create your models here.

sitelove/sitelove/views.py
from django.shortcuts import render


def home(request):
    """

    :param request:
    :return:
    """
    return render(request, 'home.html')


def nav(request):
    """

    :param request:
    :return:
    """
    return render(request, 'nav.html')

sitelove/vitrine/views.py
from django.shortcuts import render


def home(request):
    return render(request, "vitrine/home.html")


def about(request):
    return render(request, "vitrine/about.html")


def contact(request):
    return render(request, "vitrine/contact.html")

sitelove/templates/base.html
<!DOCTYPE html>
<html lang="fr">

{% load static %}
<head>
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>

    {% block title %}
    <title></title>
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}

</body>

</html>

sitelove/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Accueil</title>
{% endblock %}
{% block content %}
<p> accueil</p>
<a href="{% url 'vitrine:contact' %}" aria-label="dashboard">
    <span class="-mr-1 font-medium">Forms</span>
</a>
<a href="{% url 'vitrine:about' %}" aria-label="dashboard">
    <span class="-mr-1 font-medium">A propos</span>
</a>
<div class="flex min-h-screen bg-white">

    <div class="w-1/2 bg-cover md:block hidden"
         style="background-image:  url(https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)"></div>
    <!-- <div class="bg-no-repeat bg-right bg-cover max-w-max max-h-8 h-12 overflow-hidden">
            <img src="log_in.webp" alt="hey">
        </div> -->


    <div class="md:w-1/2 max-w-lg mx-auto my-24 px-4 py-5 shadow-none">
        <div class="mx-auto w-full max-w-lg">
            <p class="mt-3 text-lg font-semibold">Veillez remplire le formulaire d'inscription</p>
        </div>
        <form method="POST" class="p-0">
            {% csrf_token %}
            <div class="mt-5">
                <input class="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
                       required  type="text" name="nom" id="nom" placeholder="Votre nom"/>
            </div>
            <div class="mt-5">
                <input class="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
                       required type="number" name="tel" id="tel" placeholder="Votre numero de telephone"/>
            </div>
            <div class="mt-5">
                <input class="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
                       required type="email" name="email" id="email" placeholder=" Votre Email"/>
            </div>

            <div class="my-4">
                <textarea required name="message" id="message" placeholder="Message..." class="w-full h-32 bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"></textarea>
            </div>

            <div class="mt-5">
                <button type="submit"
                        class="block w-full rounded-md bg-orange-600 px-4 py-3.5 text-center text-xl font-semibold text-white shadow-sm hover:bg-blue-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                    Envoyer
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

sitelove/templates/nav.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title></title>
{% endblock %}
{% block content %}

{% endblock %}

sitelove/vitrine/templates/base.html
<!DOCTYPE html>
<html lang="fr">

{% load static %}
<head>
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>

    {% block title %}
    <title> Accueil </title>
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}

</body>

</html>

sitelove/vitrine/templates/contact.html
{% extends 'base.html' %}

{% block title %}
<title>Inscription</title>
{% endblock %}

{% block content %}
<div class="flex min-h-screen bg-white">

    <div class="w-1/2 bg-cover md:block hidden"
         style="background-image:  url(https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)"></div>
    <!-- <div class="bg-no-repeat bg-right bg-cover max-w-max max-h-8 h-12 overflow-hidden">
            <img src="log_in.webp" alt="hey">
        </div> -->


    <div class="md:w-1/2 max-w-lg mx-auto my-24 px-4 py-5 shadow-none">
        <div class="mx-auto w-full max-w-lg">
            <p class="mt-3 text-lg font-semibold">Veillez remplire le formulaire d'inscription</p>
        </div>
        <form method="POST" class="p-0">
            {% csrf_token %}
            <div class="mt-5">
                <input class="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
                       required  type="text" name="nom" id="nom" placeholder="Votre nom"/>
            </div>
            <div class="mt-5">
                <input class="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
                       required type="number" name="tel" id="tel" placeholder="Votre numero de telephone"/>
            </div>
            <div class="mt-5">
                <input class="w-full bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"
                       required type="email" name="email" id="email" placeholder=" Votre Email"/>
            </div>

            <div class="my-4">
                <textarea required name="message" id="message" placeholder="Message..." class="w-full h-32 bg-gray-100 text-gray-900 mt-2 p-3 rounded-lg focus:outline-none focus:shadow-outline"></textarea>
            </div>

            <div class="mt-5">
                <button type="submit"
                        class="block w-full rounded-md bg-orange-600 px-4 py-3.5 text-center text-xl font-semibold text-white shadow-sm hover:bg-blue-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                    Envoyer
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

sitelove/vitrine/templates/vitrine/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>A propos</title>
{% endblock %}
{% block content %}
<p>a propos</p>
<a href="{% url 'home' %}" aria-label="dashboard">
    <span class="-mr-1 font-medium">Accueil</span>
</a>
<a href="{% url 'vitrine:contact' %}" aria-label="dashboard">
    <span class="-mr-1 font-medium">Forms</span>
</a>
{% endblock content %}

sitelove/vitrine/templates/vitrine/contact.html
{% extends 'base.html' %}

{% block title %}
<title>Inscription</title>
{% endblock %}

{% block content %}
<p>Formulaire</p>
<a href="{% url 'home' %}" aria-label="dashboard">
    <span class="-mr-1 font-medium">Accueil</span>
</a>
<a href="{% url 'vitrine:about' %}" aria-label="dashboard">
    <span class="-mr-1 font-medium">A propos</span>
</a>

{% endblock content %}